name: Deployment

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 1. Set Environment Variables
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: 2. Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: 3. Create SQLite
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: 4. Generate Application key
      run: php artisan key:generate
    - name: 5. Create Database Schemes
      run: php artisan migrate
    - name: 6. Execute PHPUnit
      run: vendor/bin/phpunit

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: deploy via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            ${{ secrets.SSH_DRIVE }}
            cd ${{ secrets.SSH_FILEPATH }}
            php artisan down --message="서비스 업데이트 중입니다." --retry="10"
            git pull
            php artisan migrate
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan up
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
