name: Deployment

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 1. Set Environment Variables
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: 2. Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: 3. Create SQLite
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: 4. Generate Application key
      run: php artisan key:generate
    - name: 5. Create Database Schemes
      run: php artisan migrate
    - name: 6. Execute PHPUnit
      run: vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: deploy ftp
        uses: SamKirkland/FTP-Deploy-Action@3.1.0
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          git-ftp-args: --insecure
