name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 1. Set Environment Variables
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: 2. Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: 3. Create SQLite
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: 4. Generate Application key
      run: php artisan key:generate
    - name: 5. Create Database Schemes
      run: php artisan migrate
    - name: 6. Execute PHPUnit
      run: vendor/bin/phpunit
